name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35f8606deb8cfa4e8e3f7786b4ba309d9301c55e34b4c0040944956f81c67d68"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
