name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c9d432d53fe12cd75a2afb2ba4fbb1b754f2b496cf71d690c944b609089bf2c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
