name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef78b5db33e859f8475ece2bbbd82233d9374836aef2c7bd38b89580ec709796"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
