name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64ff46d184e80b563d74c940bba5bf01ae68c34e83524d0adad7b071ccae4b8a"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
