name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75560418051d2ed2ffd5d2f51d1dd71447664d7cce9930252db8146c12b862f1"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
