name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b14929c8e9dbfba9f2d39f81ef7b62e0baefdbb92f944c41943ee1df8a69bc0"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
