name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b018e7c72d8f2ba6a21c8fc2fa4eecdfea30b05aa673a04d0ccdeeef4bbc75c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
