name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3048b1ea7564fe1b5cfecbca058d3c68df855b8ea30e3b30f2ef99d3bc387f0b"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
