name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8aca9bab04d744d6da3f588218a2c02f1e522effb94eca3fa0012dd487be7f7"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
