name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abc7fc7a1df2717fcb698238d4614d1dadcbb853f33804a13034c29b72bc7cd8"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
