name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad4cd0a5ae99f959e42f120867bd9e5717e8e19c235542d194a50a28bb945d42"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
