name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28e47524af9680b1776691ee10f5a357d32148411515e538e0d4bf0b46c3512c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
