name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffdcf0f5b7e12350b7d4f953a75a1787c6fa302e018f88b0be8c5ab34aaf41a2"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
