name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "418fc6f3a71b20df68ecfd5750072f2ad679c7b8d3a2c687492ac33b4dc8d151"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
