name = "Create: Tomorrow"
author = "toby7002"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20f18b1c95e910c27f4a3371d5007fdf46a74acd23643a3a0ffb128038492486"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
